description = "[CRASHES] [advanced] Extracts a given area from the specified file, and displays the result."
disabled = true

[[arguments]]
name = "input"
description = "The path to the input file to parse"
type = "string"
